fix: fix the types of the `__exit__()` function
Currently, the following code does not work:

```python
irimager = nqm.irimager.IRImager()
with irimager:
    raise Error("This error breaks the context manager")
```

The following error is then thrown:

```
TypeError: __exit__(): incompatible function arguments. The following argument types are supported:
E               1. (self: nqm.irimager.IRImager, arg0: Optional[type], arg1: Optional[error_already_set], arg2: object) -> None
E
E           Invoked with: <nqm.irimager.IRImager object at 0xffff7d509970>, ...
```

This is because pybind11 does not map the Python exception to a
`pybind11::error_already_set` C++ type in this context.

Instead, we need to declare our `__exit__()` function to take a generic
`pybind11::object` type.