ci: supress pybind11 stubtest error
Mypy's `stubtest` command is returning the following error:

```console
me@user:~$ MYPYPATH=src poetry run stubtest nqm.irimager
error: nqm.irimager.IRImager is inconsistent, metaclass differs
Stub: in file src/nqm/irimager/__init__.pyi:11
N/A
Runtime:
<class 'pybind11_builtins.pybind11_type'>
```

This is because pybind11 adds a metaclass to all classes it creates,
and in our type stubs, we can't document this metaclass since it's
internal only.

In CI, we can just ignore this error, and only fail CI if there are
other errors.